name: Trigger Databricks Job
description: Trigger a Databricks Workflow Job
branding:
  icon: hard-drive
  color: blue
inputs:
  token:
    description: Databricks Authentication Token
    required: true
  host:
    description: Databricks Host URL
    required: true
  job-id:
    description: Databricks Workflow Job ID
    required: true      
  payload:
    description: the directory path to the specified chart
    default: '{}'
    required: false
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4.5.0

    - name: install-databricks-cli
      uses: microsoft/install-databricks-cli@v1.0.0

    - name: Set Credentials
      shell: bash
      run: |
        echo "DATABRICKS_HOST=${{ inputs.host }}" >> $GITHUB_ENV
        echo "DATABRICKS_TOKEN=${{ inputs.token }}" >> $GITHUB_ENV

    - name: 'Setup jq'
      uses: dcarbone/install-jq-action@v1.0.1

    - name: Run Databricks Job
      id: trigger
      shell: python
      run: |
        import requests
        import json
        import os
        def trigger_databricks_job(job_id, params):
            api_url = "${{ inputs.host }}/api/2.0/jobs/run-now"
            api_token = "${{ inputs.token }}"
            headers = {
                "Authorization": "Bearer " + api_token,
                "Content-Type": "application/json"
            }
            payload = {
                "job_id": "${{ inputs.job-id }}",
                "notebook_params": json.dumps(${{ inputs.payload }})
            }
            response = requests.post(api_url, headers=headers, data=json.dumps(payload))
            if response.status_code == 200:
                run_id = response.json()["run_id"]
                with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
                    print(f'job_run_id={run_id}', file=fh)                
            else:
                raise Exception(f"Failed to trigger the job: {response.text}")

    - name: Wait for Databricks Job to Complete
      shell: bash
      run: |
        status=$(databricks runs get --run-id ${{ steps.trigger.outputs.job_run_id }} | jq -r '.state.life_cycle_state')
        while [ "$status" == "RUNNING" ]; do
          status=$(databricks runs get --run-id ${{ steps.trigger.outputs.job_run_id }} | jq -r '.state.life_cycle_state')
          sleep 10
        done
        result=$(databricks runs get --run-id ${{ steps.trigger.outputs.job_run_id }} | jq -r '.state.result_state')
        echo "Job result: $result"
        if [ "$result" = "SUCCESS" ]; then
          echo "Job succeeded"
          exit 0
        else
          echo "Job failed"
          exit 1
        fi
